import type { EraMoment } from "@/types/era";

/**
 * 教育用の時代スナップショット。
 * 公式統計の丸め・複数国の雰囲気の合成を含む。UIとは分離する。
 */
export const PRESENT_ERA_ID = "now-2024";

export const ERA_MOMENTS: EraMoment[] = [
  {
    id: "oil-1973",
    year: 1973,
    title: "第一次石油危機",
    summary: "原油が跳ね、物価が走り、家計と為替が同時に揺れた。",
    source: "教育用の近似（当時の原油・物価・為替の雰囲気を丸めた値）",
    note: "中東情勢でエネルギー価格が急変し、輸入国の物価に波及した局面",
    worlds: {
      wage: { wageGrowth: 20, inflation: 11.7 },
      fx: { usdJpy: 270, oil: 12, importShare: 28 },
      energy: { price: 22, kwh: 280, saving: 0 },
      time: { years: 20, rate: 8 },
    },
  },
  {
    id: "inflation-1974",
    year: 1974,
    title: "狂乱物価",
    summary: "日本の賃上げは大きかったが、物価はそれ以上に走った年がある。",
    source: "教育用の近似（春闘・CPIの当時水準を丸めた値）",
    note: "名目賃金が大きく伸びても、実質の豊かさは別、という典型",
    worlds: {
      wage: { wageGrowth: 30, inflation: 23 },
      energy: { price: 28, kwh: 290, saving: 0 },
      time: { years: 20, rate: 8 },
    },
  },
  {
    id: "plaza-1985",
    year: 1985,
    title: "プラザ合意",
    summary: "ドル高是正で円は一気に高くなった。輸出企業の景色が変わった。",
    source: "教育用の近似（合意前後のドル円水準を丸めた値）",
    note: "為替は政策でも動く。円高は輸入には楽、輸出には逆風",
    worlds: {
      fx: { usdJpy: 238, oil: 27, importShare: 26 },
      stock: {
        inflationRate: 2,
        interestRate: 8,
        earningsGrowth: 8,
        peRatio: 18,
      },
    },
  },
  {
    id: "bubble-1989",
    year: 1989,
    title: "バブル末期",
    summary: "株も土地も期待が先行した。ローン金利は、いまよりずっと高い。",
    source: "教育用の近似（日経平均高値圏と住宅ローン金利の雰囲気）",
    note: "PERは当時さらに高い局面もある。このアプリでは上限40倍で表現",
    worlds: {
      stock: {
        inflationRate: 2.3,
        interestRate: 6,
        earningsGrowth: 12,
        peRatio: 40,
      },
      mortgage: { rate: 5.8, years: 25, amount: 3000 },
      commute: { minutes: 80 },
      time: { years: 20, rate: 6 },
    },
  },
  {
    id: "yen-1995",
    year: 1995,
    title: "80円の円高",
    summary: "戦後有数の円高。海外のものが安く、輸出は苦しかった。",
    source: "教育用の近似（1995年のドル円最安値圏を丸めた値）",
    note: "1ドル80円前後。いまの150円台と比べると、円の購買力がまったく違う",
    worlds: {
      fx: { usdJpy: 80, oil: 18, importShare: 27 },
      wage: { wageGrowth: 2.8, inflation: -0.1 },
    },
  },
  {
    id: "lost-1998",
    year: 1998,
    title: "金融不安とデフレの入口",
    summary: "金利は下がり、給料は止まり、株の利益も傷んだ。",
    source: "教育用の近似（不良債権問題期の金利・物価・賃金の雰囲気）",
    note: "名目が動かない世界では、実質も金利も、成長期とは別の意味になる",
    worlds: {
      stock: {
        inflationRate: 0.6,
        interestRate: 0.5,
        earningsGrowth: -10,
        peRatio: 16,
      },
      wage: { wageGrowth: 0.8, inflation: 0.6 },
      mortgage: { rate: 2.8, years: 30, amount: 3200 },
      time: { years: 20, rate: 0.3 },
    },
  },
  {
    id: "lehman-2008",
    year: 2008,
    title: "世界金融危機",
    summary: "利益が消え、原油は乱高下し、評価倍率は縮んだ。",
    source: "教育用の近似（危機年の株・原油の雰囲気を丸めた値）",
    note: "同じ年に、資産価格の下落とエネルギー価格の急変が重なった",
    worlds: {
      stock: {
        inflationRate: 1.4,
        interestRate: 2,
        earningsGrowth: -20,
        peRatio: 12,
      },
      fx: { usdJpy: 103, oil: 140, importShare: 30 },
      energy: { price: 24, kwh: 360, saving: 4 },
      wage: { wageGrowth: -0.2, inflation: 1.4 },
    },
  },
  {
    id: "fukushima-2011",
    year: 2011,
    title: "震災と超円高",
    summary: "円は75円近辺。エネルギー政策と家計の電気代が同時に論点になった。",
    source: "教育用の近似（2011年のドル円と電力コストの雰囲気）",
    note: "安全資産としての円高と、国内エネルギーの揺れが重なった年",
    worlds: {
      fx: { usdJpy: 76, oil: 111, importShare: 32 },
      energy: { price: 21, kwh: 340, saving: 6 },
      commute: { minutes: 55 },
    },
  },
  {
    id: "abenomics-2013",
    year: 2013,
    title: "アベノミクス初年",
    summary: "円安方向へ舵が切られ、株の期待は先行し、物価はまだ低かった。",
    source: "教育用の近似（2013年の為替・株・物価の雰囲気）",
    note: "政策が為替を動かし、輸出と株には追い風、輸入物価には逆風の芽",
    worlds: {
      fx: { usdJpy: 105, oil: 109, importShare: 33 },
      stock: {
        inflationRate: 0.4,
        interestRate: 0.1,
        earningsGrowth: 10,
        peRatio: 16,
      },
      wage: { wageGrowth: 0.3, inflation: 0.4 },
    },
  },
  {
    id: "neg-rate-2016",
    year: 2016,
    title: "マイナス金利",
    summary: "住宅ローンは過去最低圏。預金の複利は、ほとんど動かなくなった。",
    source: "教育用の近似（2016年の住宅ローン・預金金利の雰囲気）",
    note: "借りる側は軽いが、置く側の時間は味方になりにくい",
    worlds: {
      mortgage: { rate: 0.6, years: 35, amount: 3600 },
      time: { years: 20, rate: 0 },
      stock: {
        inflationRate: -0.1,
        interestRate: 0,
        earningsGrowth: 4,
        peRatio: 18,
      },
    },
  },
  {
    id: "covid-2020",
    year: 2020,
    title: "コロナ初年",
    summary: "金利は底、通勤は消え、企業利益は一時的に傷ついた。",
    source: "教育用の近似（2020年の市場・通勤・賃金の雰囲気）",
    note: "同じ危機でも、株の評価と日常の移動は別の速度で動いた",
    worlds: {
      stock: {
        inflationRate: 0.5,
        interestRate: 0.5,
        earningsGrowth: -5,
        peRatio: 28,
      },
      commute: { minutes: 15 },
      wage: { wageGrowth: -0.5, inflation: 0 },
      mortgage: { rate: 0.7, years: 35, amount: 3800 },
      time: { years: 20, rate: 0.1 },
    },
  },
  {
    id: "inflation-2022",
    year: 2022,
    title: "インフレと利上げ",
    summary: "物価と金利が同時に上がり、円もエネルギーも揺れた。",
    source: "教育用の近似（2022年の米インフレと円安・燃料高の雰囲気）",
    note: "株は評価が縮み、ローンと電気代と輸入物価が同時に話題になった年",
    worlds: {
      stock: {
        inflationRate: 8,
        interestRate: 4.5,
        earningsGrowth: -2,
        peRatio: 18,
      },
      wage: { wageGrowth: 2.2, inflation: 2.5 },
      fx: { usdJpy: 137, oil: 100, importShare: 38 },
      energy: { price: 42, kwh: 380, saving: 5 },
      mortgage: { rate: 1, years: 35, amount: 4200 },
    },
  },
  {
    id: PRESENT_ERA_ID,
    year: 2024,
    title: "いま",
    summary: "賃上げは戻りつつあり、円は弱い。金利は世界と日本で温度差がある。",
    source: "教育用の近似（2024年前後の賃金・為替・金利の雰囲気）",
    note: "比較の基準年。統計の確定値ではなく、触って比べるための定点",
    worlds: {
      stock: {
        inflationRate: 2.7,
        interestRate: 4.2,
        earningsGrowth: 8,
        peRatio: 22,
      },
      wage: { wageGrowth: 5.1, inflation: 2.7 },
      mortgage: { rate: 1.3, years: 35, amount: 4500 },
      fx: { usdJpy: 151, oil: 81, importShare: 36 },
      time: { years: 20, rate: 0.2 },
      commute: { minutes: 40 },
      energy: { price: 31, kwh: 350, saving: 10 },
    },
  },
];
